/**
 * MetaFab API
 * Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.5.1
 * Contact: metafabproject@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import org.openapitools.client.model.WalletModel;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class AuthProfile200Response {
  
  @SerializedName("id")
  private String id = null;
  @SerializedName("ecosystemId")
  private String ecosystemId = null;
  @SerializedName("walletId")
  private String walletId = null;
  @SerializedName("connectedWalletId")
  private String connectedWalletId = null;
  @SerializedName("username")
  private String username = null;
  @SerializedName("accessToken")
  private String accessToken = null;
  @SerializedName("updatedAt")
  private String updatedAt = null;
  @SerializedName("createdAt")
  private String createdAt = null;
  @SerializedName("walletDecryptKey")
  private String walletDecryptKey = null;
  @SerializedName("wallet")
  private WalletModel wallet = null;
  @SerializedName("custodialWallet")
  private WalletModel custodialWallet = null;

  /**
   * This field has not had a description added.
   **/
  @ApiModelProperty(value = "This field has not had a description added.")
  public String getId() {
    return id;
  }
  public void setId(String id) {
    this.id = id;
  }

  /**
   * This field has not had a description added.
   **/
  @ApiModelProperty(value = "This field has not had a description added.")
  public String getEcosystemId() {
    return ecosystemId;
  }
  public void setEcosystemId(String ecosystemId) {
    this.ecosystemId = ecosystemId;
  }

  /**
   * This field has not had a description added.
   **/
  @ApiModelProperty(value = "This field has not had a description added.")
  public String getWalletId() {
    return walletId;
  }
  public void setWalletId(String walletId) {
    this.walletId = walletId;
  }

  /**
   * This field has not had a description added.
   **/
  @ApiModelProperty(value = "This field has not had a description added.")
  public String getConnectedWalletId() {
    return connectedWalletId;
  }
  public void setConnectedWalletId(String connectedWalletId) {
    this.connectedWalletId = connectedWalletId;
  }

  /**
   * This field has not had a description added.
   **/
  @ApiModelProperty(value = "This field has not had a description added.")
  public String getUsername() {
    return username;
  }
  public void setUsername(String username) {
    this.username = username;
  }

  /**
   * This field has not had a description added.
   **/
  @ApiModelProperty(value = "This field has not had a description added.")
  public String getAccessToken() {
    return accessToken;
  }
  public void setAccessToken(String accessToken) {
    this.accessToken = accessToken;
  }

  /**
   * This field has not had a description added.
   **/
  @ApiModelProperty(value = "This field has not had a description added.")
  public String getUpdatedAt() {
    return updatedAt;
  }
  public void setUpdatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
  }

  /**
   * This field has not had a description added.
   **/
  @ApiModelProperty(value = "This field has not had a description added.")
  public String getCreatedAt() {
    return createdAt;
  }
  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }

  /**
   * This field has not had a description added.
   **/
  @ApiModelProperty(value = "This field has not had a description added.")
  public String getWalletDecryptKey() {
    return walletDecryptKey;
  }
  public void setWalletDecryptKey(String walletDecryptKey) {
    this.walletDecryptKey = walletDecryptKey;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public WalletModel getWallet() {
    return wallet;
  }
  public void setWallet(WalletModel wallet) {
    this.wallet = wallet;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public WalletModel getCustodialWallet() {
    return custodialWallet;
  }
  public void setCustodialWallet(WalletModel custodialWallet) {
    this.custodialWallet = custodialWallet;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuthProfile200Response authProfile200Response = (AuthProfile200Response) o;
    return (this.id == null ? authProfile200Response.id == null : this.id.equals(authProfile200Response.id)) &&
        (this.ecosystemId == null ? authProfile200Response.ecosystemId == null : this.ecosystemId.equals(authProfile200Response.ecosystemId)) &&
        (this.walletId == null ? authProfile200Response.walletId == null : this.walletId.equals(authProfile200Response.walletId)) &&
        (this.connectedWalletId == null ? authProfile200Response.connectedWalletId == null : this.connectedWalletId.equals(authProfile200Response.connectedWalletId)) &&
        (this.username == null ? authProfile200Response.username == null : this.username.equals(authProfile200Response.username)) &&
        (this.accessToken == null ? authProfile200Response.accessToken == null : this.accessToken.equals(authProfile200Response.accessToken)) &&
        (this.updatedAt == null ? authProfile200Response.updatedAt == null : this.updatedAt.equals(authProfile200Response.updatedAt)) &&
        (this.createdAt == null ? authProfile200Response.createdAt == null : this.createdAt.equals(authProfile200Response.createdAt)) &&
        (this.walletDecryptKey == null ? authProfile200Response.walletDecryptKey == null : this.walletDecryptKey.equals(authProfile200Response.walletDecryptKey)) &&
        (this.wallet == null ? authProfile200Response.wallet == null : this.wallet.equals(authProfile200Response.wallet)) &&
        (this.custodialWallet == null ? authProfile200Response.custodialWallet == null : this.custodialWallet.equals(authProfile200Response.custodialWallet));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.ecosystemId == null ? 0: this.ecosystemId.hashCode());
    result = 31 * result + (this.walletId == null ? 0: this.walletId.hashCode());
    result = 31 * result + (this.connectedWalletId == null ? 0: this.connectedWalletId.hashCode());
    result = 31 * result + (this.username == null ? 0: this.username.hashCode());
    result = 31 * result + (this.accessToken == null ? 0: this.accessToken.hashCode());
    result = 31 * result + (this.updatedAt == null ? 0: this.updatedAt.hashCode());
    result = 31 * result + (this.createdAt == null ? 0: this.createdAt.hashCode());
    result = 31 * result + (this.walletDecryptKey == null ? 0: this.walletDecryptKey.hashCode());
    result = 31 * result + (this.wallet == null ? 0: this.wallet.hashCode());
    result = 31 * result + (this.custodialWallet == null ? 0: this.custodialWallet.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuthProfile200Response {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  ecosystemId: ").append(ecosystemId).append("\n");
    sb.append("  walletId: ").append(walletId).append("\n");
    sb.append("  connectedWalletId: ").append(connectedWalletId).append("\n");
    sb.append("  username: ").append(username).append("\n");
    sb.append("  accessToken: ").append(accessToken).append("\n");
    sb.append("  updatedAt: ").append(updatedAt).append("\n");
    sb.append("  createdAt: ").append(createdAt).append("\n");
    sb.append("  walletDecryptKey: ").append(walletDecryptKey).append("\n");
    sb.append("  wallet: ").append(wallet).append("\n");
    sb.append("  custodialWallet: ").append(custodialWallet).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
