/**
 * MetaFab API
 *  Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.1.3
 * Contact: metafabproject@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import org.openapitools.client.model.OasAnyTypeNotMapped;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class CreateCollectionItemRequestAttributesInner {
  
  @SerializedName("trait_type")
  private String traitType = null;
  @SerializedName("value")
  private OasAnyTypeNotMapped value = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getTraitType() {
    return traitType;
  }
  public void setTraitType(String traitType) {
    this.traitType = traitType;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public OasAnyTypeNotMapped getValue() {
    return value;
  }
  public void setValue(OasAnyTypeNotMapped value) {
    this.value = value;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateCollectionItemRequestAttributesInner createCollectionItemRequestAttributesInner = (CreateCollectionItemRequestAttributesInner) o;
    return (this.traitType == null ? createCollectionItemRequestAttributesInner.traitType == null : this.traitType.equals(createCollectionItemRequestAttributesInner.traitType)) &&
        (this.value == null ? createCollectionItemRequestAttributesInner.value == null : this.value.equals(createCollectionItemRequestAttributesInner.value));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.traitType == null ? 0: this.traitType.hashCode());
    result = 31 * result + (this.value == null ? 0: this.value.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateCollectionItemRequestAttributesInner {\n");
    
    sb.append("  traitType: ").append(traitType).append("\n");
    sb.append("  value: ").append(value).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
