/**
 * MetaFab API
 * Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.5.1
 * Contact: metafabproject@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.Map;
import org.openapitools.client.model.ProfilePermissionsValue;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class CreateProfilePlayerRequest {
  
  @SerializedName("username")
  private String username = null;
  @SerializedName("permissions")
  private Map<String, ProfilePermissionsValue> permissions = null;

  /**
   * The username to assign to the created player.
   **/
  @ApiModelProperty(required = true, value = "The username to assign to the created player.")
  public String getUsername() {
    return username;
  }
  public void setUsername(String username) {
    this.username = username;
  }

  /**
   * A properly formatted permissions object that validates against the MetaFab profile permissions schema.
   **/
  @ApiModelProperty(value = "A properly formatted permissions object that validates against the MetaFab profile permissions schema.")
  public Map<String, ProfilePermissionsValue> getPermissions() {
    return permissions;
  }
  public void setPermissions(Map<String, ProfilePermissionsValue> permissions) {
    this.permissions = permissions;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateProfilePlayerRequest createProfilePlayerRequest = (CreateProfilePlayerRequest) o;
    return (this.username == null ? createProfilePlayerRequest.username == null : this.username.equals(createProfilePlayerRequest.username)) &&
        (this.permissions == null ? createProfilePlayerRequest.permissions == null : this.permissions.equals(createProfilePlayerRequest.permissions));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.username == null ? 0: this.username.hashCode());
    result = 31 * result + (this.permissions == null ? 0: this.permissions.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateProfilePlayerRequest {\n");
    
    sb.append("  username: ").append(username).append("\n");
    sb.append("  permissions: ").append(permissions).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
