/**
 * MetaFab API
 * Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.5.1
 * Contact: metafabproject@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class SetPlayerConnectedWalletRequest {
  
  @SerializedName("address")
  private String address = null;
  @SerializedName("nonce")
  private Integer nonce = null;
  @SerializedName("signature")
  private String signature = null;
  public enum ChainEnum {
     ARBITRUM,  ARBITRUMGOERLI,  ARBITRUMNOVA,  AVALANCHE,  AVALANCHEFUJI,  ETHEREUM,  FANTOM,  FANTOMTEST,  GOERLI,  MATIC,  MATICMUMBAI,  THUNDERCORE,  THUNDERCORETESTNET, 
  };
  @SerializedName("chain")
  private ChainEnum chain = null;

  /**
   * The address of the external wallet to connect to the player.
   **/
  @ApiModelProperty(required = true, value = "The address of the external wallet to connect to the player.")
  public String getAddress() {
    return address;
  }
  public void setAddress(String address) {
    this.address = address;
  }

  /**
   * Any positive integer that hasn't been used previously to connect or disconnect this external wallet. Must be the same nonce used to generate the `signature`.
   **/
  @ApiModelProperty(required = true, value = "Any positive integer that hasn't been used previously to connect or disconnect this external wallet. Must be the same nonce used to generate the `signature`.")
  public Integer getNonce() {
    return nonce;
  }
  public void setNonce(Integer nonce) {
    this.nonce = nonce;
  }

  /**
   * A signature string generated by signing a keccak256 hash generated with abiCoder encode arguments of `[ 'bytes32', 'address', 'bool', 'address', 'uint256' ]` and `[ keccak256(gameId), delegate wallet approved (player's custodial wallet address), true, external wallet address, any unused nonce number ]`.
   **/
  @ApiModelProperty(required = true, value = "A signature string generated by signing a keccak256 hash generated with abiCoder encode arguments of `[ 'bytes32', 'address', 'bool', 'address', 'uint256' ]` and `[ keccak256(gameId), delegate wallet approved (player's custodial wallet address), true, external wallet address, any unused nonce number ]`.")
  public String getSignature() {
    return signature;
  }
  public void setSignature(String signature) {
    this.signature = signature;
  }

  /**
   * The blockchain you want to support this wallet connection on. If you need to support multiple blockchains, make multiple requests using different `chain` arguments. Support for new blockchains are added over time.
   **/
  @ApiModelProperty(required = true, value = "The blockchain you want to support this wallet connection on. If you need to support multiple blockchains, make multiple requests using different `chain` arguments. Support for new blockchains are added over time.")
  public ChainEnum getChain() {
    return chain;
  }
  public void setChain(ChainEnum chain) {
    this.chain = chain;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SetPlayerConnectedWalletRequest setPlayerConnectedWalletRequest = (SetPlayerConnectedWalletRequest) o;
    return (this.address == null ? setPlayerConnectedWalletRequest.address == null : this.address.equals(setPlayerConnectedWalletRequest.address)) &&
        (this.nonce == null ? setPlayerConnectedWalletRequest.nonce == null : this.nonce.equals(setPlayerConnectedWalletRequest.nonce)) &&
        (this.signature == null ? setPlayerConnectedWalletRequest.signature == null : this.signature.equals(setPlayerConnectedWalletRequest.signature)) &&
        (this.chain == null ? setPlayerConnectedWalletRequest.chain == null : this.chain.equals(setPlayerConnectedWalletRequest.chain));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.address == null ? 0: this.address.hashCode());
    result = 31 * result + (this.nonce == null ? 0: this.nonce.hashCode());
    result = 31 * result + (this.signature == null ? 0: this.signature.hashCode());
    result = 31 * result + (this.chain == null ? 0: this.chain.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SetPlayerConnectedWalletRequest {\n");
    
    sb.append("  address: ").append(address).append("\n");
    sb.append("  nonce: ").append(nonce).append("\n");
    sb.append("  signature: ").append(signature).append("\n");
    sb.append("  chain: ").append(chain).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
