/**
 * MetaFab API
 * Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.5.1
 * Contact: metafabproject@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import org.openapitools.client.model.WalletModel;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class UpdateProfilePlayer200ResponseAllOf {
  
  @SerializedName("wallet")
  private WalletModel wallet = null;
  @SerializedName("custodialWallet")
  private WalletModel custodialWallet = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public WalletModel getWallet() {
    return wallet;
  }
  public void setWallet(WalletModel wallet) {
    this.wallet = wallet;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public WalletModel getCustodialWallet() {
    return custodialWallet;
  }
  public void setCustodialWallet(WalletModel custodialWallet) {
    this.custodialWallet = custodialWallet;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateProfilePlayer200ResponseAllOf updateProfilePlayer200ResponseAllOf = (UpdateProfilePlayer200ResponseAllOf) o;
    return (this.wallet == null ? updateProfilePlayer200ResponseAllOf.wallet == null : this.wallet.equals(updateProfilePlayer200ResponseAllOf.wallet)) &&
        (this.custodialWallet == null ? updateProfilePlayer200ResponseAllOf.custodialWallet == null : this.custodialWallet.equals(updateProfilePlayer200ResponseAllOf.custodialWallet));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.wallet == null ? 0: this.wallet.hashCode());
    result = 31 * result + (this.custodialWallet == null ? 0: this.custodialWallet.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateProfilePlayer200ResponseAllOf {\n");
    
    sb.append("  wallet: ").append(wallet).append("\n");
    sb.append("  custodialWallet: ").append(custodialWallet).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
